// Octopus Server API MCP server — generated by mcpify. Do not hand-edit.

use std::sync::OnceLock;

use rusqlite::Connection;

use crate::data::store::search_endpoints;
use crate::services::embedding_service::embed;

/// Guards the completeness check below so it only queries the two row
/// counts once per process instead of on every `search` call — cheap
/// either way, but there is no reason to repeat a check whose answer
/// cannot change during the process's lifetime (the embedded store is
/// read-only at runtime).
static COMPLETENESS_CHECKED: OnceLock<()> = OnceLock::new();

/// `populate_embeddings` is the only writer of `semantic_endpoints` and
/// fails loudly at index-build time if it ever leaves that table short of
/// `endpoints` (row-count parity, not just non-empty) — but a store built
/// before that check existed, or restored from an older artifact, can
/// still reach here under-populated. This does not change the `search`
/// tool's success/`[]` contract for legitimately-empty results; it only
/// surfaces a diagnostic for an operator, since search itself works
/// correctly (just over an incomplete corpus) either way.
fn warn_if_incomplete(conn: &Connection) {
    COMPLETENESS_CHECKED.get_or_init(|| {
        let counts: rusqlite::Result<(i64, i64)> = conn.query_row(
            "SELECT (SELECT COUNT(*) FROM endpoints), \
                    (SELECT COUNT(*) FROM semantic_endpoints)",
            [],
            |row| Ok((row.get(0)?, row.get(1)?)),
        );
        if let Ok((endpoints_count, semantic_count)) = counts
            && semantic_count < endpoints_count
        {
            tracing::warn!(
                endpoints_count,
                semantic_count,
                "semantic_endpoints is missing embeddings for some operations; \
                 search results may be incomplete — re-run populate_embeddings"
            );
        }
    });
}

/// Semantic similarity lookup matching a natural-language query against
/// candidate API operations (PRD §1.5) — so an LLM never needs the full
/// OpenAPI spec in context to find the right operation.
pub fn search_operations(
    conn: &Connection,
    query: &str,
    limit: usize,
) -> anyhow::Result<serde_json::Value> {
    warn_if_incomplete(conn);
    let query_embedding = embed(query)?;
    let results = search_endpoints(conn, &query_embedding, limit)?;
    Ok(serde_json::to_value(results)?)
}
